[build]
  publish = "dist"
  command = "npm run netlify-build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/assets/*.mjs"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.js.map"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

# Handle routing for single page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
